apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: kanidm-operator-rolebinding-namespaced
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: kanidm-operator-role-namespaced
subjects:
  - kind: ServiceAccount
    name: kanidm-operator-account
    namespace: kanidm-system
