---
apiVersion: kanidm.github.io/v1alpha1
kind: OAuth2Client
metadata:
  name: forgejo-oauth
  namespace: kanidm
spec:
  kanidmName: kanidm-instance
  name: forgejo
  displayName: Forgejo
  origin: https://git.example.com
  prefer-short-username: true
  scope-map:
    group: git-users
    scopes:
      - openid
      - email
  secret:
    labels:
      secret-kind: oauth2-client
...
