name: Build, test, and deploy to Docker Hub

env:
  # This forces the python/requests library to use the system CA bundle, which is where we added our self-signed CA
  REQUESTS_CA_BUNDLE: /etc/ssl/certs/ca-certificates.crt

on:
  # Pushes and tags trigger the full workflow
  push:
    branches:
      - "master"
    tags:
      - "v*"
  # Pull requests only trigger the unit tests
  pull_request:
    branches:
      - "master"
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Extract metadata (tags, labels) for docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }} # this will be ghcr.io/SIMULATAN/kanidm-operator
      - name: Login to Docker Hub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: ${{ github.event_name != 'pull_request' }} # Don't push images for pull requests
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
